### ISSUE TITLE
后台业务管理窗口里面，类型分驻场专员、业务员、经纪公司，渠道经理，但是在修改用户窗口里面只有案场专员、经纪公司、渠道经理三个角色，统一一下

### ISSUE THREAD

**Issue by bianyibin1979** [ydapp/ydapp#40]

**Comment by guanzheyuan** [comment]
修改用户窗口中，修改app管理员的时候，类型只有app管理员一种（app管理员只能有admin管理员新增，并且只能存在一个），修改用户类型为案场专员、经纪公司、渠道经理其中一个的时候，修改类型有三种（这三种可以互相修改），修改业务员的时候，类型只有一种，修改页面中的类型都是对应的用户新增页面的类型，系统用户类型一共有四种，但是这四种类型不是同时存在，是根据不同的用户角色去定义的。
