### ISSUE TITLE
后台汇总信息只有管理员能看，经济公司只能分业务员账号，其他人不能查看后台信息。

### ISSUE THREAD

**Issue by bianyibin1979** [ydapp/ydapp#54]

**Comment by leasonlive** [comment]
后台权限
1、admin管理员和app管理员跟以前一样，可以查看所有的
2、经纪公司只能维护本公司的经纪人
3、驻场专员、渠道经理、经纪人只能查看联系人，不能维护。

该需求修改需要等待用户最终确定。
