### ISSUE TITLE
前台和后台的人员排列，除了驻场专员，渠道经理，管理员置顶外，其他的经纪公司业务员用公司的归属和加入的时间来排序，同一个公司的人员，经济公司排第一，业务员按照姓名拼音排列

### ISSUE THREAD

**Issue by bianyibin1979** [ydapp/ydapp#55]

**Comment by leasonlive** [comment]
对人员进行编码，采用10位编码规则，字母加四位数字
管理为A，从1开始，第一个管理员是A0001
app管理员D，从1开始，第一个app管理员为D0001
驻场专业为G，从1开始，第一个驻场专业为G0001
渠道经理为J，从1开始，第一个渠道经理为J0001
经纪公司为M，从1开始，第一个经纪公司为M0001，
业务员为P，从属于经纪公司，从1开始，第一个经纪人为P0001，业务员的实际代码为经纪公司代码+业务员代码，比如M0001P0001

建立一张表专门维护这个序列，并在用户表中增加一个person_code字段，用于存储人员编码值。
表名为pis_persion_code(parent,key,value),存储的值如('',A,1)或者（‘’，M，10）或者（‘M0001’，P，20）之类的
提供一个服务得到人员下一个编码的PersonCodeService.getNextCode(codeType)
该方法用户获取数据库中的key等于codeType的value的值，对值进行加1，并更新数据库。

在培训的时候，首先对人员编码（person_code）字段排序，然后对用户名称（name）排序
